# Generated by Django 6.0.5 on 2026-05-07 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Опис')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сума')),
                ('transaction_type', models.CharField(choices=[('debit', 'Дебет'), ('credit', 'Кредит')], max_length=10, verbose_name='Тип')),
            ],
        ),
    ]
